---
title: "Unepic"
author: "Nanaya" 
date: "`r format(Sys.time(), 'Le %d/%m/%Y')`"
output:
  prettydoc::html_pretty:
    theme: cayman
---

```{r, include = FALSE}
knitr::opts_chunk$set(echo = FALSE,label_list=TRUE)# Setting Knitr base option
lapply(c("knitr"),# and flexidashboard
       require,# through the require function
       character.only = TRUE)# ensuring reading
options(encoding = 'UTF-8')# ensuring encoding
```

<!---
=> Tiddyverse ? Soit-même
=> Tibble ? Idem
=> Publish ? Plus tard
--->

```{r prep}
seed = c(paste0(4,4,6,round(runif(1,0,9)),5,5),paste0(7,7,7,round(runif(1,0,9)),7,7))
#sam = c(4,7)
#crow = c(4,7)
#iron = c(6,7)
#ju = c(2,5)
#nim = c(5,7)
#sun = c(5,7)
# loading db
db = read.csv2("Races_Sraces_DD5.csv",#loading the data
                     header = TRUE)# and telling that there are headers.
histo = read.csv(file = "historiques.csv",header = FALSE)
player = matrix(rep(0,6*10),nrow = 6, ncol = 10, byrow = TRUE)# making a matrix to store all results
rownames(player) = c("CrimsonSam","CrowHazard","Ironboots",# Naming said matrix rows
                     "Nanaya","Nimlas","Sunchine")# Using player name
colnames(player) = c("Race (sous-race)","Historique (guildless)","Trait 1","Trait 2",# Listing our variables
                     "Lien","Idéale","Défaut","Allié de la Guilde","Rival de la Guilde","Non Guild Contact")# and naming the matrix column accordingly
```

## Premier tirage

------------------------------------

```{r seed1}
set.seed(seed[1])# Setting the seed
player[1:6,1] = sample(levels(db[,2]),6,replace = TRUE)
player[1:6,2] = paste(sample(histo$V1,6,replace = TRUE))
sub = c()
for (i in 1:6) {# 6 players
  sub = paste(sample(x = db[which(player[i,1] == db[,2]),1],size = 1,replace = FALSE))
  player[i,1] = ifelse(player[i,1] == sub,paste(player[i,1]),paste(player[i,1],sub))
  player[i,c(3:4,8:9)] = sample(1:8,4,replace = TRUE) ; player[i,10] = sample(1:10,1)
  player[i,5:7] = sample(1:6,3, replace = TRUE)# Assigning random values last v.a.
}
player[,1:2] = casefold(player[,1:2])
kable(t(player))# Printing the table
```

------------------------------------

## Second tirage

------------------------------------

```{r seed2}
set.seed(seed[2])# Setting the seed
player[1:6,1] = sample(levels(db[,2]),6,replace = TRUE)
player[1:6,2] = paste(sample(histo$V1,6,replace = TRUE))
sub = c()
for (i in 1:6) {# 6 players
  sub = paste(sample(x = db[which(player[i,1] == db[,2]),1],size = 1,replace = FALSE))
  player[i,1] = ifelse(player[i,1] == sub,paste(player[i,1]),paste(player[i,1],sub))
  player[i,c(3:4,8:9)] = sample(1:8,4,replace = TRUE) ; player[i,10] = sample(1:10,1)
  player[i,5:7] = sample(1:6,3, replace = TRUE)# Assigning random values last v.a.
}
player[,1:2] = casefold(player[,1:2])
kable(t(player))# Printing the table
```

------------------------------------
